---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app
  namespace: k8s
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: "venkateshkasa996/nodeapp1:latest"
        ports:
          - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: k8s
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3005
    port: 3005
    
