---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ravilogindeploy
  namespace: k8s
  labels:
    app: ravilogin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ravilogin
  template:
    metadata:
      labels:
        app: ravilogin
    spec:
      containers:
      - name: ravilogin-c
        image: "venkateshkasa996/ravilogin:latest"
        ports:
          - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: ravilogin
  namespace: k8s
spec:
  selector:
    app: ravilogin
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3005
    port: 3005
    
